"""empty message

Revision ID: 7b65a49c3a8a
Revises: f5c051dbc85a
Create Date: 2022-04-28 09:35:42.161148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b65a49c3a8a'
down_revision = 'f5c051dbc85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.execute('UPDATE "user" SET full_name = \'unknown\' WHERE full_name IS NULL;')
    op.alter_column('user','full_name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
