"""empty message

Revision ID: 8dc2c05f5892
Revises: 
Create Date: 2022-05-15 12:48:58.916503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8dc2c05f5892'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Empleados')
    op.drop_table('Tareas')
    op.drop_table('Administradores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Administradores',
    sa.Column('dni_admin', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('nombres', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellidos', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fecha_anadido', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('dni_admin', name='Administradores_pkey'),
    sa.UniqueConstraint('correo', name='Administradores_correo_key')
    )
    op.create_table('Tareas',
    sa.Column('id_tarea', sa.INTEGER(), server_default=sa.text('nextval(\'"Tareas_id_tarea_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('completo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_tarea', name='Tareas_pkey')
    )
    op.create_table('Empleados',
    sa.Column('dni_empleado', sa.INTEGER(), server_default=sa.text('nextval(\'"Empleados_dni_empleado_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('nombres', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('apellidos', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('genero', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('fecha_anadido', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_modificado', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('dni_empleado', name='Empleados_pkey')
    )
    # ### end Alembic commands ###
