"""empty message

Revision ID: ad0b9c353486
Revises: 7b65a49c3a8a
Create Date: 2022-04-28 11:26:42.277975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0b9c353486'
down_revision = '7b65a49c3a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile_phone', sa.String(length=20), nullable=True))
    op.execute('UPDATE "user" SET mobile_phone = \'unknown\' WHERE mobile_phone IS NULL;')
    op.alter_column('user','mobile_phone', nullable=False)

    op.add_column('user', sa.Column('password', sa.String(length=200), nullable=True))
    op.execute('UPDATE "user" SET password = \'unknown\' WHERE password IS NULL;')
    op.alter_column('user','password', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('user', 'mobile_phone')
    # ### end Alembic commands ###
